name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install bashly
        run: sudo gem install bashly

      - name: Build
        run: bashly generate

      - name: Publish nightly release
        if: startsWith(github.ref, 'refs/tags/') == false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete nightly --yes || true
          git push origin :nightly || true
          gh release create nightly --prerelease --title "Nightly" --target $GITHUB_SHA motch

      - if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $TAG_NAME --title "$TAG_NAME" --target $GITHUB_SHA motch
